
package es.pruebas.j2ee6.jax.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RegistroTelematicoServiceImpleService", targetNamespace = "http://ws.jax.j2ee6.pruebas.es/", wsdlLocation = "http://emilio-pc:8080/jaxws001/RegistroTelematicoServiceImpleService?wsdl")
public class RegistroTelematicoServiceImpleService
    extends Service
{

    private final static URL REGISTROTELEMATICOSERVICEIMPLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.pruebas.j2ee6.jax.ws.RegistroTelematicoServiceImpleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.pruebas.j2ee6.jax.ws.RegistroTelematicoServiceImpleService.class.getResource(".");
            url = new URL(baseUrl, "http://emilio-pc:8080/jaxws001/RegistroTelematicoServiceImpleService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://emilio-pc:8080/jaxws001/RegistroTelematicoServiceImpleService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTROTELEMATICOSERVICEIMPLESERVICE_WSDL_LOCATION = url;
    }

    public RegistroTelematicoServiceImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistroTelematicoServiceImpleService() {
        super(REGISTROTELEMATICOSERVICEIMPLESERVICE_WSDL_LOCATION, new QName("http://ws.jax.j2ee6.pruebas.es/", "RegistroTelematicoServiceImpleService"));
    }

    /**
     * 
     * @return
     *     returns RegistroTelematicoServiceImple
     */
    @WebEndpoint(name = "RegistroTelematicoServiceImplePort")
    public RegistroTelematicoServiceImple getRegistroTelematicoServiceImplePort() {
        return super.getPort(new QName("http://ws.jax.j2ee6.pruebas.es/", "RegistroTelematicoServiceImplePort"), RegistroTelematicoServiceImple.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistroTelematicoServiceImple
     */
    @WebEndpoint(name = "RegistroTelematicoServiceImplePort")
    public RegistroTelematicoServiceImple getRegistroTelematicoServiceImplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jax.j2ee6.pruebas.es/", "RegistroTelematicoServiceImplePort"), RegistroTelematicoServiceImple.class, features);
    }

}
